title: Moje Portfolio
description: >
  Portfolio Mateusza Bogacza
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mateusz-bogacz-collegiumwitelona.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

sass:
  sass_dir: css